import type { Metadata } from "next";
import localFont from "next/font/local";
import { Dancing_Script } from "next/font/google";
import "./globals.css";

const chaneyUltraExtended = localFont({
  src: "./fonts/chaney-ultraextended.woff2",
  variable: "--font-chaney",
  display: "swap",
});

const safiroMedium = localFont({
  src: "./fonts/safiro-medium.woff2",
  variable: "--font-safiro",
  display: "swap",
});

const dancingScript = Dancing_Script({
  variable: "--font-dancing",
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://cdn.jsdelivr.net/npm/remixicon@4.7.0/fonts/remixicon.css"
          rel="stylesheet"
        />
      </head>
      <body
        className={`${chaneyUltraExtended.variable} ${safiroMedium.variable} ${dancingScript.variable} antialiased`}
      >
        {children}
      </body>
    </html>
  );
}
